config/routes.rb
Producer::Application.routes.draw do
  
  root to: "pages#index"
  
  match '/home'  , to: 'pages#index' , as: :home
  match '/prices', to: 'pages#prices', as: :prices
  match '/tour'  , to: 'pages#tour'  , as: :tour
  
  namespace :admin do
    resources :posts
    resources :categories, except: :show
  end
  
  resources :categories

  resources :posts do
    resources :comments, only: [:create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  with_options allow_blank: true do |c|
    c.validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    c.validates_format_of :url  , with: /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  validates_presence_of :title, :body, :author, :slug, :published_at
  validates_uniqueness_of :slug
  validates_inclusion_of :draft, in: [true,false]
  validates_associated :author
  
  before_validation :generate_slug

  scope :published, lambda {
    where("draft = ? AND published_at < ?", false, Time.current)
  }
  
  scope :search, lambda { |terms|
    where("title LIKE :t OR body LIKE :t", t: "%#{terms}%")
  }

  def to_param
    "#{id}-#{slug}"
  end
  
  protected

  def generate_slug
    self.slug = title unless slug.present?
    self.slug = slug.parameterize
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, foreign_key: :author_id

  validates_presence_of   :email, :first_name, :last_name
  validates_uniqueness_of :email
  validates_format_of     :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def full_name
    "#{first_name} #{last_name}".capitalize
  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController

  before_filter :load_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
    respond_with @categories
  end

  def new
    @category = Category.new
    respond_with @category
  end

  def edit
  end

  def create
    @category = Category.new(params[:category])
    flash[:notice] = 'Category was successfully created.' if @category.save
    respond_with @category, :location => admin_categories_path
  end

  def update
    flash[:notice] = 'Category was successfully updated.' if @category.update_attributes(params[:category])
    respond_with @category, :location => admin_categories_path
  end

  def destroy
    @category.destroy
    respond_with @category, :location => admin_categories_path
  end
  
  protected
  
  def load_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  before_filter :load_post     , only: [:show, :edit, :update, :destroy]
  before_filter :load_resources, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.all
    respond_with @posts
  end

  def show
    respond_with @post do |format|
      format.html { render :layout => "application" }
    end
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def edit
  end

  def create
    @post = Post.new(params[:post])

    flash[:notice] = 'Post was successfully created.' if @post.save
    respond_with @post, :location => admin_posts_path
  end

  def update
    flash[:notice] = 'Post was successfully updated.' if @post.update_attributes(params[:post])
    respond_with @post, :location => edit_admin_post_path(@post)
  end

  def destroy
    @post.destroy
    respond_with @post, :location => admin_posts_path
  end

  protected

  def load_post
    @post = Post.find(params[:id])
  end

  def load_resources
    @authors = User.all
    @categories = Category.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :html, :json, :xml, :js
  before_filter :change_locale
  
  protected
  
  def change_locale
    I18n.locale = params[:locale] || :en
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post    = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    
    flash[:alert] = 'Fail to receive the comment. Double check the fields' unless @comment.save
    redirect_to post_path(@post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
  
  def prices
  end
  
  def tour
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :categories

  def index
    @posts = Post.scoped
    @posts = @posts.search(params[:search]) if params[:search]
    @posts = @category.posts if @category.present?
    @posts = @posts.published

    respond_with @posts
  end

  def show
    @post = Post.published.find(params[:id])
    respond_with @post
  end

  protected

  def categories
    @categories = Category.all
    @category   = Category.find(params[:category_id]) if params[:category_id]
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper

  def link_to_new(model, url, html_options = {})
    link_to t('new', model: model.model_name.human), url, html_options
  end
  
  def link_to_edit(url, html_options = {})
    html_options.reverse_merge!(class: 'green')
    link_to t('edit'), url, html_options
  end
  
  def link_to_destroy(url, html_options = {})
    html_options.reverse_merge!(confirm: t('confirm'), method: :delete, class: 'red')
    link_to t('destroy'), url, html_options
  end
  
  def translate_attribute(model, attribute)
    model.human_attribute_name(attribute)
  end
  alias_method :ta, :translate_attribute
  
  def section(title='', &block)
    content_tag :div, class: 'section' do
      html = ''
      html = content_tag :h3, title if title.present?
      html = content_tag :div, class: 'in', &block
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
     render partial: 'shared/error_messages', locals: { object: object }
  end

  def flash_messages
    flash.collect do |key,msg|
      content_tag(:p, msg, id: key, class: 'flash_message')
    end.join.html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def gravatar_image_tag(email, html_options = {})
    email = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/#{email}?size=48", html_options
  end

  def comment_author(name, url="")
    name = "Anonymous Coward" unless name.present?
    url.present? ? link_to(name, url, :target => "_blank") : name
  end
  
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
	<%= error_messages_for @category %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'Category name' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button' %> or <%= link_to 'cancel', admin_categories_path %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h2>Editing category</h2>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h2>Posts Categories</h2>

<% if @categories.present? %>
<ul class="list">
  <% @categories.each do |category| %>
    <%= content_tag_for :li, category, class: cycle(:odd, :even) do %>
      <%= link_to category.name, [:admin, category] %>

      <div class="right">
        <%= link_to_edit [:edit, :admin, category] %>,
        <%= link_to_destroy [:admin, category] %>
      </div>
    <% end %>
  <% end %>
</ul>
<% else %>
  <p>You don't have any posts yet.</p>
<% end %>

<hr class="thick" />

<div class="bar">
  <div class="right">
    <%= link_to 'New category', new_admin_category_path, class: "button" %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h2>New category</h2>

<%= render 'form' %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
   <%= error_messages_for @post %>

   <div id="body">
     <div class="field">
       <%= f.label :author_id, t('.author') %>
       <%= f.collection_select :author_id, @authors, :id, :full_name %>
     </div>

     <div class="field">
       <%= f.text_field :title, :placeholder => ta(Post, :title), :class => "title" %>
     </div>

     <div class="field">
       <%= f.text_area :excerpt, :placeholder => ta(Post, :excerpt), :rows => 5, :cols => 70 %>
     </div>

     <div class="field">
       <%= f.text_area :body, :placeholder => ta(Post, :body), :rows => 30, :cols => 70 %>
     </div>

     <div class="field">
       <%= f.check_box :draft %>
       <%= f.label :draft %>
     </div>

     <hr class="thick" />

     <p>
       <%= f.submit :class => "button" %> or <%= link_to t("cancel"), admin_posts_path %>
     </p>
   </div>

   <div id="sidebar">
     <%= section t('.categories') do %>
       <ul class="categories-field">
         <% @categories.each do |c| %>
           <li><%= check_box_tag "post[category_ids][]", 
           c.id, @post.categories.include?(c) %> 
           <%= c.name %></li>
         <% end %>
       </ul>
       <div class="bar">
         <%= link_to_new Category, new_admin_category_path, :class => "button right" %>
       </div>
       <br/>
     <% end %>

     <hr/>

     <%= section do %>
       <div class="field">
         <%= f.label :published_at %><br/>
         <%= f.date_select :published_at, :use_short_month => true %>
       </div>
     <% end %>

     <hr/>

     <%= section  do %>
       <div class="field">
         <%= f.label :slug, t('.slug') %><br/>
         <%= f.text_field :slug, :size => 27 %>
       </div>
     <% end %>
   </div>

 <% end %>

app/views/admin/posts/edit.html.erb
<h2>
	<%= t ".title" %> <%= link_to 'Preview', [:admin, @post], class: 'button right', target: '_blank' %>
</h2>

<%= render 'form' %>

app/views/admin/posts/index.html.erb
<h2>Posts</h2>

<% if @posts.present? %>
<ul class="list">
  <% @posts.each do |post| %>
    <%= content_tag_for :li, post, :class => cycle(:odd, :even) do %>
      <%= link_to post.title.titleize, [:admin, post] %>

      <div class="right">
        <%= link_to_edit [:edit, :admin, post] %>,
        <%= link_to_destroy [:admin, post] %>
      </div>
    <% end %>
  <% end %>
</ul>
<% else %>
  <p><%= t :empty, collection: "posts" %></p> <!-- t = I18n.translate -->
<% end %>

<hr class="thick" />

<div class="bar">
  <div class="right">
    <%= link_to_new Post, new_admin_post_path, :class => "button" %>
  </div>
</div>

app/views/admin/posts/new.html.erb
<h2><%= t ".title" %></h2>

<%= render 'form' %>

app/views/admin/posts/show.html.erb
<div id="column1">
	<h2><%= @post.title %></h2>

	<div id="post">
		<%= simple_format @post.body %>
	</div>
</div>

app/views/comments/_comment.html.erb
<%= div_for comment, :class => "comment" do %>

  <div class="author">
    <div class="avatar"><%= gravatar_image_tag comment.email %></div>
    <div class="meta">
      <span class="name"><%= comment_author(comment.author, comment.url) %></span><br/>
      <span class="date">Posted <%= time_ago_in_words comment.created_at %> ago</span>
    </div>
  </div>

  <div class="body" style="margin-bottom:20px;">
    <%= comment.body %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [post, comment] do |f| %>
	<%= error_messages_for comment %>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 10, cols: 90 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag "admin", "scaffold" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="wrapper">
    <div id="header">
      <div id="main-nav">
        <ul>
          <li><a>Dashboard</a></li>
          <li><a>Posts</a></li>
          <li><a>Media</a></li>
          <li><a>Changelog</a></li>
          <li><a>Inquiries</a></li>
        </ul>
      </div>
    </div>

    <div id="content-wrapper">
      <div id="content">
        <div class="in">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<html>
<head>
  <title>Producer</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="wrapper">
    <div id="header">
      <div id="logo">
        <%= image_tag "logo_header.png", :class => "middle" %>
      </div>

      <div id="main-nav">
        <ul>
          <li>
            <%= link_to root_path do %>
              HOME <br/><span>DISCOVER OUR
              <br/> AWESOME PRODUCT</span>
            <% end %>
          </li>
          <li>
            <a>TOUR <br/><span>DISCOVER WHY IT'LL
              <br/> MAKE YOUR LIFE BETTER</span></a>
          </li>
          <li>
            <%= link_to posts_path do %>
              BLOG <br/><span>NEWS, TIPS AND OUR
              <br/> RANDOM THOUGHTS</span>
            <% end %>
          </li>
          <li>
            <a>FAQ <br/><span>FREQUENTLY ASKED
            <br/> QUESTION</span></a>
          </li>
          <li>
            <a>CONTACT <br/><span>YOU'RE NOT ALONE
            <br/> GET IN TOUCH</span></a>
          </li>
          <li>
            <a>PRICE <br/><span>SMALL AMOUNT
            <br/> FOR A BIG BENEFIT</span></a>
          </li>
        </ul>
      </div>
    </div>

    <div id="content">
      <%= flash_messages %>
      <%= yield %>
    </div>

    <div id="footer">
      <div id="footer-nav">
        <ul>
          <li><a>HOME</a></li>
          <li><a>TOUR</a></li>
          <li><a>BLOG</a></li>
          <li><a>FAQ</a></li>
          <li><a>CONTACT</a></li>
          <li><a>PRICE</a></li>
        </ul>
      </div>
    </div>
  </div>

</body>
</html>

app/views/pages/index.html.erb
<%= image_tag "banner.jpg", :class => "frame" %>

<div id="content">
 <div id="column1">
   <h2>Who is already on Rails?</h2>
   <p>Tens of thousands of Rails applications are already live. People are using Rails in the tiniest part-time operations to the biggest companies.</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
 </div>

 <div id="column2">
   <h2>Who is behind it?</h2>
   <p>Rails was created in 2003 by David Heinemeier Hansson and has since been extended by the Rails core team, more than 1,400 contributors, and supported by a vibrant ecosystem.</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
 </div>
</div>

app/views/pages/index.pt-BR.html.erb
<%= image_tag "banner.jpg", :class => "frame" %>

<div id="content">
  <div id="column1">
    <h2>Quem já utiliza Rails?</h2>
    <p>Dezenas de centenas de aplicações Rails já estão rodando em todo o mundo. Pessoas estão utilizando o Rails em diversas situações, desde pequena operações pequenas até gigantes corporações.</p>
  </div>

  <div id="column2">
    <h2>Quem está por trás?</h2>
    <p>Rails foi criado em 2003 por David Heinemeier Hansson e desde então foi expandido pelo time central do Rails, mais de 1.400 contribuidores e suportado por um vibrante ecossistema.</p>
  </div>
</div>

app/views/pages/prices.html.erb
prices

app/views/pages/tour.html.erb
tour

app/views/posts/_sidebar.html.erb
<div id="column2">

  <h3>Search</h3>

  <%= form_tag posts_path, :method => :get do %>
    <%= text_field_tag :search, "",
          :placeholder => "key words here",
          :size => 30,
          :type => "search",
          :class => "search-field" %>
  <% end %>

  <h3>Categories</h3>

  <ul class="squared">
    <% @categories.each do |category| %>
      <li><%= link_to_unless_current category.name, posts_path(category_id: category.id) %></li>
    <% end %>
  </ul>

  <h3>Keep in touch</h3>

  <ul class="squared">
    <li>FOLLOW US ON <strong style="color:#d7412c">TWITTER</strong></li>
    <li>SUBSCRIBE TO OUR <strong style="color:#d7412c">FEED</strong></li>
  </ul>

</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "blog" %>

<div id="column1">
  <% if @posts.present? %>

    <% @posts.each do |post| %>
      <h2><%= link_to post.title.titleize, post %></h2>

      <div id="post">
        <%= simple_format post.excerpt %>

        <p><%= link_to "continue ...", post %></p>
      </div>
    <% end %>

  <% else %>
    <h3>Zero posts founded.</h3>
  <% end %>
</div>

<%= render "sidebar" %>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "blog" %>

<div id="column1">

  <h2><%= @post.title %></h2>

  <div id="post">
    <%= simple_format @post.body %>
  </div>

  <hr/>

  <h3>Comments</h3>

  <div id="comments">
  <% if @post.comments.any? %>
    <%= render :partial => @post.comments %>
  <% else %>
    <p>Nobody commented this post yet.</p>
  <% end %>
  </div>

  <%= render "comments/form", :post => @post, :comment => Comment.new %>
</div>

<%= render "sidebar" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= t 'errors.template.header', model: object.class.model_name.human %></h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>